export default {
  BUTTON_ACCEPT_COOKIE: '#hs-eu-confirmation-button',
  MENU_LETS_CONENCT: '.lets-connect-menu',
  FIRST_NAME: '[name="firstname"]',
  LAST_NAME: '[name="lastname"]',
  COUNTRY: '[name="country"]',
  EMAIL: '[name="email"]',
  ORGANIZATION: '[name="company_organization"]',
  MESSAGE: '[name="message"]',
  MOBILE: '[class="hs-input"][inputmode="tel"]',
  MESSAGE: '[name="message"]',
  SUBMIT_BUTTON: '.hs-button.primary.large',
  SUCCESS_MESSAGE_DIV: '.submitted-message div',
  GOOGLE_CAPTCHA_SKIP: '#recaptcha-verify-button',
}